# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-13 21:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Parroquia', '0002_auto_20170709_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='nombre',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='direccion',
            field=models.CharField(max_length=15),
        ),
    ]
