# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-13 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parroquia', '0004_album_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(max_length=30)),
                ('cuenta', models.CharField(max_length=15)),
            ],
        ),
    ]
