# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-13 23:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Parroquia', '0005_donaciones'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Donaciones',
            new_name='Donacion',
        ),
        migrations.RenameField(
            model_name='imagen',
            old_name='file',
            new_name='foto',
        ),
    ]
